### ISSUE TITLE
安装不了啦

### ISSUE THREAD

**Issue by peter29ljf** [Yonsm/MiService#34]
$ pip3 install miservice
Collecting miservice
  Using cached miservice-2.0.1.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\peter\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\peter\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\peter\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\peter\AppData\Local\Temp\pip-build-env-f9_my6xa\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\peter\AppData\Local\Temp\pip-build-env-f9_my6xa\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\peter\AppData\Local\Temp\pip-build-env-f9_my6xa\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\peter\AppData\Local\Temp\pip-build-env-f9_my6xa\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
        File "C:\Users\peter\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
          return f.read()
        File "C:\Users\peter\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2062: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jjiikkkk** [comment]
这种方法很多人都实现不了 你去申请一个小米小爱的API吧 官网 头条有操作 用那种方法好了

**Comment by peter29ljf** [comment]
安装在服务器端可以，本地不行。本地安装老一点的版本可以

**Comment by peter29ljf** [comment]
但安装在服务器，试过腾讯和GOOGLE的，可以安装，不能执行，可能被封了

**Comment by peter29ljf** [comment]
https://github.com/yihong0618/MiService 这个可以安装在本地

**Comment by jjiikkkk** [comment]
我是觉得 他们写这个源代码的时候 为什么没有考虑到 这个问题
几个人的源代码互相改改抄抄，都忽略这个问题
