### ISSUE TITLE
安装最新版本报错呢

### ISSUE THREAD

**Issue by yuan6785** [Yonsm/MiService#47]
pip install -U MiService==2.1.2
Collecting MiService==2.1.2
  Using cached miservice-2.1.2.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/yuanxiao/.pyenv/versions/py3.11_virtualenv_test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/yuanxiao/.pyenv/versions/py3.11_virtualenv_test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/yuanxiao/.pyenv/versions/py3.11_virtualenv_test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yz/wr4mf5654m306_wpj23bx7vm0000gn/T/pip-build-env-q62g21_v/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yz/wr4mf5654m306_wpj23bx7vm0000gn/T/pip-build-env-q62g21_v/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/yz/wr4mf5654m306_wpj23bx7vm0000gn/T/pip-build-env-q62g21_v/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/yz/wr4mf5654m306_wpj23bx7vm0000gn/T/pip-build-env-q62g21_v/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/private/var/folders/yz/wr4mf5654m306_wpj23bx7vm0000gn/T/pip-install-w73i_04y/miservice_8561a24430bf4f04b3ca223dff320819/micli.py", line 2, in <module>
          from aiohttp import ClientSession
      ModuleNotFoundError: No module named 'aiohttp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by CHEN-HONGLIN** [comment]
是呢，我也是报同样的错。     from aiohttp import ClientSession
      ModuleNotFoundError: No module named 'aiohttp'

**Comment by CHEN-HONGLIN** [comment]
aiohttp 这个模块已经安装了 ，还是报错 ModuleNotFoundError: No module named 'aiohttp'

**Comment by jasonhorga** [comment]
我也出这个问题，很奇怪，突然就出现了...

**Comment by jasonhorga** [comment]
我更新了一下wheel，然后发现yarl报错，又把yarl删掉重新装了一下，然后发现miservice安装没错误了。。。

**Comment by andylovephysics** [comment]
Same problem, but I solved with another approach: manual installation.

```
environment: Ubuntu 24.04
python 3.12
```

First I set up a venv of python 3.12 and activate it.

Then, clone into this repository.

`git clone https://github.com/Yonsm/MiService.git`

then

`cd MiService`

then 

`pip install .`

After that, if no error occurs, try `micli`.

If it returns:
```bash
MiService %s - XiaoMi Cloud Service

Usage: The following variables must be set:
           export MI_USER=<Username>
           export MI_PASS=<Password>
           export MI_DID=<Device ID|Name>

Get Props: micli <siid[-piid]>[,...]
           micli 1,1-2,1-3,1-4,2-1,2-2,3
Set Props: micli <siid[-piid]=value>[,...]
           micli 2=#60,2-2=#false,3=test
Do Action: micli <siid[-piid]> <arg1|#NA> [...] 
           micli 2 #NA
           micli 5 Hello
           micli 5-4 Hello #1

Call MIoT: micli <cmd=prop/get|/prop/set|action> <params>
           micli action '{"did":"267090026","siid":5,"aiid":1,"in":["Hello"]}'

Call MiIO: micli /<uri> <data>
           micli /home/device_list '{"getVirtualModel":false,"getHuamiDevices":1}'

Devs List: micli list   
           micli list Light true 0

MIoT Spec: micli spec  
           micli spec
           micli spec speaker
           micli spec xiaomi.wifispeaker.lx04
           micli spec urn:miot-spec-v2:device🔈0000A015:xiaomi-lx04:1

MIoT Decode: micli decode <ssecurity> <nonce> <data> 
```
Then it is correctly installed.
