### ISSUE TITLE
centos7.9 执行《pip install aiohttp aiofiles miservice》命令，安装miservice 2.1.2版本报错呢？

### ISSUE THREAD

**Issue by CHEN-HONGLIN** [Yonsm/MiService#50]
![QQ浏览器截图20240811161830](https://github.com/user-attachments/assets/b81450c2-763d-4847-a8a4-8bad1cfa34da)
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ozpd4sii/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ozpd4sii/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ozpd4sii/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ozpd4sii/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/tmp/pip-install-fpnkp8z8/miservice_ab36a529de144f429e8703e5104b8a60/micli.py", line 2, in <module>
          from aiohttp import ClientSession
      ModuleNotFoundError: No module named 'aiohttp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by CHEN-HONGLIN** [comment]
如图是python版本号，aiohttp都已经安装了的！
![QQ浏览器截图20240811162711](https://github.com/user-attachments/assets/0b783f35-cb35-4e50-8795-e16ba8062042)

**Comment by XiaoMiHongZhaJi** [comment]
同

**Comment by lpe234** [comment]
```yml
# requirements
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install miservice -i https://pypi.tuna.tsinghua.edu.cn/simple
```

分开安装可以

**Comment by Weiitit** [comment]
先把项目git clone到本地 /tmp/MiService：
```shell
git clone git clone https://github.com/Yonsm/MiService.git /tmp/MiService
``` 
如图，编辑里面的/tmp/MiService/setup.py文件第 17 和 22 行：
17行 前面加#注释掉
22行 =后改成'2.1.2'
![2024-10-07 151332](https://github.com/user-attachments/assets/a3d3ced6-b7a6-4845-a4f5-ad3aadd9461d)
保存后安装：
```shell
pip3 install /tmp/MiService
```
